import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from './components/navigation/Sidebar';
import Header from './components/navigation/Header';
import { ToastContainer } from 'react-toastify';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const isAuthenticated = false;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Header />
        <Sidebar />*/}
        {/* {children}  */}
          {isAuthenticated ? (
              <div className="flex">
                <>
                  <Header />
                  <Sidebar />
                </>
                <main className={`mt-8 ml-0 md:ml-64 transition-all duration-300 ease-in-out`}>
                  {children}
                </main>
              </div>
            ) : (
              <div>
                {children}
              </div>
            )}
        <ToastContainer className="foo" style={{ width: "2000px" }} />
      </body>
    </html>
  );
}
